# Generated by Django 3.2.9 on 2021-12-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20211201_1213'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='skudata',
            index_together={('subcategory', 'location', 'department', 'category')},
        ),
    ]
